// =============================================================================
// Responsible for all .meta file operations — creating, reading, and deleting
// =============================================================================

import fs from "fs";
import path from "path";

// -----------------------------------------------------------------------------
// getMetaPath(filePath)
//
// Pure helper — derives the .meta file path from a given file path.
// This is the single source of truth for how meta file paths are named.
//
// Example:
//   "C:/project/assets/models/robot.glb"
//    → "C:/project/assets/models/robot.glb.meta"
//
// Parameters:
//   filePath {string} — Absolute path to the actual file.
//
// Returns: {string} The absolute path to the corresponding .meta file.
// -----------------------------------------------------------------------------
const getMetaPath = (filePath) => {
  return filePath + ".meta";
};

// -----------------------------------------------------------------------------
// metaExistsFor(filePath)
//
// Checks whether a .meta file exists for the given file.
//
// Parameters:
//   filePath {string} — Absolute path to the actual file.
//
// Returns: {boolean} true if the .meta file exists, false otherwise.
// -----------------------------------------------------------------------------
const metaExistsFor = (filePath) => {
  const metaPath = getMetaPath(filePath);
  return fs.existsSync(metaPath);
};

// -----------------------------------------------------------------------------
// createMeta(filePath, guid, type)
//
// Creates a .meta sidecar file next to the given file.
// This is called immediately after any new file is added to the project
// (whether imported by the user or created by the app itself like a new scene).
//
// The .meta file stores:
//   - guid         : The permanent unique identifier for this file.
//   - type         : What kind of asset this is ("model", "texture", "scene", "krita").
//   - originalName : The file's name at the time the meta was created.
//   - createdAt    : ISO timestamp of when this meta file was created.
//
// Parameters:
//   filePath {string} — Absolute path to the actual file.
//   guid     {string} — The GUID generated by GuidService for this file.
//   type     {string} — Asset type: "model" | "texture" | "scene" | "krita".
//
// Returns: {void}
// -----------------------------------------------------------------------------
const createMeta = (filePath, guid, type) => {
  const metaPath = getMetaPath(filePath);

  const metaContent = {
    guid,
    type,
    originalName: path.basename(filePath),
    createdAt: new Date().toISOString(),
  };

  fs.writeFileSync(metaPath, JSON.stringify(metaContent, null, 2), "utf-8");
};

// -----------------------------------------------------------------------------
// readMeta(filePath)
//
// Reads and parses the .meta file for the given file.
// Used during reconciliation and when resolving asset info by file path.
//
// Parameters:
//   filePath {string} — Absolute path to the actual file (NOT the .meta file).
//
// Returns: {object} Parsed meta object containing guid, type, originalName, createdAt.
//
// Throws: If the .meta file does not exist or cannot be parsed.
// -----------------------------------------------------------------------------
const readMeta = (filePath) => {
  const metaPath = getMetaPath(filePath);

  if (!fs.existsSync(metaPath)) {
    throw new Error(`Meta file not found for: ${filePath}`);
  }

  const raw = fs.readFileSync(metaPath, "utf-8");

  try {
    return JSON.parse(raw);
  } catch (err) {
    throw new Error(`Failed to parse meta file for: ${filePath}. Reason: ${err.message}`);
  }
};

// -----------------------------------------------------------------------------
// deleteMeta(filePath)
//
// Deletes the .meta file corresponding to the given file.
// Called during:
//   - Asset or scene deletion (initiated from within the app).
//   - Reconciliation Pass 1 (when the actual file no longer exists on disk).
//   - Reconciliation Pass 3 (orphaned meta cleanup).
//
// Parameters:
//   filePath {string} — Absolute path to the actual file (NOT the .meta file).
//
// Returns: {void}
// -----------------------------------------------------------------------------
const deleteMeta = (filePath) => {
  const metaPath = getMetaPath(filePath);

  if (fs.existsSync(metaPath)) {
    fs.unlinkSync(metaPath);
  }
  // If the meta file doesn't exist, we silently do nothing.
  // This prevents crashes during reconciliation where the state may be partially inconsistent.
};

export { getMetaPath, metaExistsFor, createMeta, readMeta, deleteMeta };